"""invoice status default and idempotency key

Revision ID: 90554ddf8b26
Revises: 2f4f3ed01359
Create Date: 2026-10-03 18:52:18.130122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '90554ddf8b26'
down_revision = '2f4f3ed01359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.alter_column('invoices', 'statut',
               existing_type=postgresql.ENUM('BROUILLON', 'ENVOYEE', 'PAYEE', 'EN_RETARD', 'ANNULEE', name='invoicestatus'),
               server_default='BROUILLON',
               nullable=False)
    op.create_unique_constraint(None, 'invoices', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='unique')
    op.alter_column('invoices', 'statut',
               existing_type=postgresql.ENUM('BROUILLON', 'ENVOYEE', 'PAYEE', 'EN_RETARD', 'ANNULEE', name='invoicestatus'),
               server_default=None,
               nullable=True)
    op.drop_column('invoices', 'idempotency_key')
    # ### end Alembic commands ###
