"""employee entity and explicit delete behaviour

Revision ID: f1f441a6bc13
Revises: 4a98ca00f1cd
Create Date: 2026-10-04 16:04:22.513867

"""
from alembic import op
import sqlalchemy as sa


revision = 'f1f441a6bc13'
down_revision = '4a98ca00f1cd'
branch_labels = None
depends_on = None


def upgrade():
    # Policies first. payslips_read and the leave policies compare employee_id
    # to app.user_id, and employee_id is about to stop being a users.id.
    # PostgreSQL also refuses to alter the type of a column a policy references,
    # so these must go before the ALTER regardless.
    for policy, table in (
        ("payslips_read", "payslips"), ("payslips_write", "payslips"),
        ("leave_requests_read", "leave_requests"), ("leave_requests_write", "leave_requests"),
        ("team_members_read", "team_members"), ("team_members_write", "team_members"),
        ("team_members_owner_all", "team_members"),
    ):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {table}")

    # Different key spaces now: employee_id references employees.id while
    # valide_par_id references users.id, so a row-local comparison is
    # meaningless. Replaced by a trigger at the end of this revision.
    op.execute("ALTER TABLE leave_requests DROP CONSTRAINT IF EXISTS ck_leave_no_self_validation")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('hired_on', sa.Date(), nullable=False),
    sa.Column('annual_entitlement_days', sa.Integer(), nullable=False),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'ON_LEAVE', 'TERMINATED', name='employmentstatus'), server_default='ACTIVE', nullable=False),
    sa.CheckConstraint('annual_entitlement_days >= 0 AND annual_entitlement_days <= 365', name='ck_employees_entitlement'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.drop_index('ix_team_members_id', table_name='team_members')
    op.drop_table('team_members')
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('invoices_cree_par_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_client_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_client_id_fkey', 'invoices', 'clients', ['client_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('invoices_cree_par_id_fkey', 'invoices', 'users', ['cree_par_id'], ['id'], ondelete='RESTRICT')
    # Order matters: the existing foreign key points at users.id (varchar), so
    # the column type cannot change while it is in place. Drop, retype, repoint.
    #
    # postgresql_using is required because there is no implicit VARCHAR ->
    # INTEGER cast. The tables are empty, so nothing is actually converted;
    # on a populated database this step would need a real data migration
    # mapping each users.id to its new employees.id.
    op.drop_constraint('leave_requests_employee_id_fkey', 'leave_requests', type_='foreignkey')
    op.drop_constraint('leave_requests_valide_par_id_fkey', 'leave_requests', type_='foreignkey')
    op.alter_column('leave_requests', 'employee_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='employee_id::integer')
    op.create_foreign_key('leave_requests_employee_id_fkey', 'leave_requests', 'employees', ['employee_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('leave_requests_valide_par_id_fkey', 'leave_requests', 'users', ['valide_par_id'], ['id'], ondelete='RESTRICT')

    op.drop_constraint('payslips_employee_id_fkey', 'payslips', type_='foreignkey')
    op.alter_column('payslips', 'employee_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='employee_id::integer')
    op.create_foreign_key('payslips_employee_id_fkey', 'payslips', 'employees', ['employee_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    # ---- row-level security for the new table and the re-pointed ones -------
    op.execute("ALTER TABLE employees ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE employees FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY employees_owner_all ON employees "
        "FOR ALL TO dixpertia_owner USING (true) WITH CHECK (true)"
    )
    # An employee sees their own record; admin and accountant see everyone.
    op.execute("""
        CREATE POLICY employees_read ON employees
        FOR SELECT TO dixpertia_app
        USING (
            nullif(current_setting('app.user_role', true), '') IN ('admin', 'accountant')
            OR user_id = nullif(current_setting('app.user_id', true), '')
        )
    """)
    op.execute("""
        CREATE POLICY employees_write ON employees
        FOR ALL TO dixpertia_app
        USING (nullif(current_setting('app.user_role', true), '') = 'admin')
        WITH CHECK (nullif(current_setting('app.user_role', true), '') = 'admin')
    """)

    # The identity on the connection is still a users.id, so these resolve
    # through employees rather than comparing to employee_id directly.
    op.execute("""
        CREATE POLICY payslips_read ON payslips
        FOR SELECT TO dixpertia_app
        USING (
            nullif(current_setting('app.user_role', true), '') IN ('admin', 'accountant')
            OR employee_id IN (
                SELECT id FROM employees
                WHERE user_id = nullif(current_setting('app.user_id', true), '')
            )
        )
    """)
    op.execute("""
        CREATE POLICY payslips_write ON payslips
        FOR ALL TO dixpertia_app
        USING (nullif(current_setting('app.user_role', true), '') IN ('admin', 'accountant'))
        WITH CHECK (nullif(current_setting('app.user_role', true), '') IN ('admin', 'accountant'))
    """)
    op.execute("""
        CREATE POLICY leave_requests_read ON leave_requests
        FOR SELECT TO dixpertia_app
        USING (
            nullif(current_setting('app.user_role', true), '') = 'admin'
            OR employee_id IN (
                SELECT id FROM employees
                WHERE user_id = nullif(current_setting('app.user_id', true), '')
            )
        )
    """)
    op.execute("""
        CREATE POLICY leave_requests_write ON leave_requests
        FOR ALL TO dixpertia_app
        USING (
            nullif(current_setting('app.user_role', true), '') = 'admin'
            OR employee_id IN (
                SELECT id FROM employees
                WHERE user_id = nullif(current_setting('app.user_id', true), '')
            )
        )
        WITH CHECK (
            nullif(current_setting('app.user_role', true), '') = 'admin'
            OR employee_id IN (
                SELECT id FROM employees
                WHERE user_id = nullif(current_setting('app.user_id', true), '')
            )
        )
    """)

    # Supports both the policy subqueries above and the user -> employee lookup.
    op.execute("CREATE INDEX IF NOT EXISTS ix_employees_user_id ON employees (user_id)")

    # ---- no self-validation, now that it spans two tables -------------------
    op.execute("""
        CREATE OR REPLACE FUNCTION trg_leave_no_self_validation()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        BEGIN
            IF NEW.valide_par_id IS NOT NULL
               AND EXISTS (
                   SELECT 1 FROM employees e
                   WHERE e.id = NEW.employee_id
                     AND e.user_id = NEW.valide_par_id
               )
            THEN
                RAISE EXCEPTION 'An employee cannot validate their own leave request';
            END IF;
            RETURN NEW;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER leave_no_self_validation
        BEFORE INSERT OR UPDATE ON leave_requests
        FOR EACH ROW EXECUTE FUNCTION trg_leave_no_self_validation()
    """)


def downgrade():
    op.execute("DROP TRIGGER IF EXISTS leave_no_self_validation ON leave_requests")
    op.execute("DROP FUNCTION IF EXISTS trg_leave_no_self_validation()")
    for policy, table in (
        ("employees_read", "employees"), ("employees_write", "employees"),
        ("employees_owner_all", "employees"),
        ("payslips_read", "payslips"), ("payslips_write", "payslips"),
        ("leave_requests_read", "leave_requests"), ("leave_requests_write", "leave_requests"),
    ):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    # Same ordering constraint as the upgrade, mirrored: the column cannot
    # change type while a foreign key references it, and the recreated key
    # points at users.id (varchar), so the type must change first.
    op.drop_constraint('payslips_employee_id_fkey', 'payslips', type_='foreignkey')
    op.alter_column('payslips', 'employee_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='employee_id::varchar')
    op.create_foreign_key('payslips_employee_id_fkey', 'payslips', 'users', ['employee_id'], ['id'])

    op.drop_constraint('leave_requests_employee_id_fkey', 'leave_requests', type_='foreignkey')
    op.drop_constraint('leave_requests_valide_par_id_fkey', 'leave_requests', type_='foreignkey')
    op.alter_column('leave_requests', 'employee_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='employee_id::varchar')
    op.create_foreign_key('leave_requests_valide_par_id_fkey', 'leave_requests', 'users', ['valide_par_id'], ['id'])
    op.create_foreign_key('leave_requests_employee_id_fkey', 'leave_requests', 'users', ['employee_id'], ['id'])
    op.drop_constraint('invoices_client_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_cree_par_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_client_id_fkey', 'invoices', 'clients', ['client_id'], ['id'])
    op.create_foreign_key('invoices_cree_par_id_fkey', 'invoices', 'users', ['cree_par_id'], ['id'])
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.create_table('team_members',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('initials', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatarUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='team_members_pkey')
    )
    op.create_index('ix_team_members_id', 'team_members', ['id'], unique=False)
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    # drop_table leaves the enum type behind; without this a later upgrade
    # fails with 'type employmentstatus already exists'.
    op.execute("DROP TYPE IF EXISTS employmentstatus")
    # ### end Alembic commands ###
